title: '10K Boxing'
permalink: none
url: 'http://10kboxing.com'
timezone: Europe/London
exclude:
    - Gemfile
    - Gemfile.lock
analytics:
    provider: google_analytics
sharing:
    provider:
        - facebook
        - twitter
        - google
        - linkedin
        - pinterest
        - stumbleupon
    limit: '3'
profiles:
    provider:
        - facebook
        - twitter
        - youtube
        - instagram
    facebook: 'https://www.facebook.com/10kBoxing?fref=ts'
    twitter: 'https://twitter.com/10kboxing'
    pinterest: 'https://pinterest.com/brightonjapan'
    youtube: 'https://youtube.com/10kboxing'
    instagram: 'https://instagram.com/badytouray'
defaults:
    -
        scope:
            path: ''
            type: posts
        values:
            layout: page
    -
        scope:
            path: ''
            type: pages
        values:
            layout: page
    -
        scope:
            path: ''
            type: events
        values:
            layout: event
    -
        scope:
            path: ''
            type: gallery
        values:
            layout: gallery
    -
        scope:
            path: ''
            type: fighters
        values:
            layout: fighter
    -
        scope:
            path: ''
            type: models
        values:
            layout: model
collections:
    content:
        output: true
        permalink: ':path.html'
    events:
        output: true
        permalink: 'events/:path.html'
    fighters:
        output: true
        permalink: ':path.html'
    models:
        output: true
        permalink: ':path.html'
    gallery:
        output: true
description: '10K Boxing'
relative_permalinks: 'false'
v: 4
baseurl: /
cdn: //cdn.abemedia.co.uk/0x0/10kboxing/
comments:
    provider: '1'
advanced:
    xs_w: 263
    xs_h: 0
    sm_w: 432
    sm_h: 0
    md_w: 800
    md_h: 0
    lg_w: 1280
    lg_h: 0
    xl_w: 1920
    xl_h: 0
