title: '10K Boxing'
permalink: none
url: 'http://beta.abemedia.co.uk/badymanagement'
timezone: Europe/London
exclude:
    - Gemfile
    - Gemfile.lock
analytics:
    provider: google_analytics
sharing:
    provider:
        - facebook
        - twitter
        - google
        - linkedin
        - pinterest
        - stumbleupon
    limit: '3'
profiles:
    provider:
        - facebook
        - twitter
        - pinterest
    facebook: 'https://facebook.com/brightonjapanfestival'
    twitter: 'https://twitter.com/brightonjapan15'
    pinterest: 'https://pinterest.com/brightonjapan'
defaults:
    -
        scope:
            path: ''
            type: posts
        values:
            layout: page
    -
        scope:
            path: ''
            type: pages
        values:
            layout: page
    -
        scope:
            path: ''
            type: gallery
        values:
            layout: gallery
collections:
    content:
        output: true
        permalink: ':path.html'
    team:
        output: true
        permalink: ':path.html'
    gallery:
        output: true
description: '10K Boxing'
relative_permalinks: 'false'
v: 1n
baseurl: /
cdn: //cdn.donlabs.com/0x0/badymanagement/
